In [1]:
import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

print("Environment ready.")
print("Power BI dataset preparation initialized.")

Environment ready.
Power BI dataset preparation initialized.

In [17]:
input_path = Path("../data/processed/airbnb_powerbi.csv")
output_dir = Path("../data/processed/powerbi")

output_dir.mkdir(parents=True, exist_ok=True)

df = pd.read_csv(input_path, parse_dates=["last_review"])

print("Dataset loaded successfully.")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully.
Shape: (219981, 21)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,has_reviews,currency,price_eur,log_price_view
0,6369,"Rooftop terrace room , ensuite bathroom",13660,Simon,Chamartín,Hispanoamérica,40.46,-3.68,private room,60,1,78,2020-09-20,0.58,1.00,180.00,Madrid,1,EUR,60.00,4.11
1,21853,Bright and airy room,83531,Abdel,Latina,Cármenes,40.40,-3.74,private room,31,4,33,2018-07-15,0.42,2.00,364.00,Madrid,1,EUR,31.00,3.47
2,23001,Apartmento Arganzuela- Madrid Rio,82175,Jesus,Arganzuela,Legazpi,40.39,-3.70,entire home/apt,50,15,0,NaT,0.00,7.00,1.00,Madrid,0,EUR,50.00,3.93
3,24805,Gran Via Studio Madrid,346366726,A,Centro,Universidad,40.42,-3.71,entire home/apt,92,5,10,2020-03-01,0.13,1.00,72.00,Madrid,1,EUR,92.00,4.53
4,26825,Single Room whith private Bathroom,114340,Agustina,Arganzuela,Legazpi,40.39,-3.69,private room,26,2,149,2020-03-12,1.12,1.00,365.00,Madrid,1,EUR,26.00,3.30

In [6]:
df_powerbi = df.copy()

# Business-friendly field for host behavior
df_powerbi["host_type"] = np.where(
    df_powerbi["calculated_host_listings_count"].fillna(1) > 1,
    "Multi-listing host",
    "Single-listing host"
)

# Business-friendly field for review status
df_powerbi["review_status"] = np.where(
    df_powerbi["has_reviews"] == 1,
    "Has reviews",
    "No reviews"
)

df_powerbi.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,has_reviews,currency,price_eur,log_price_view,host_type,review_status
0,6369,"Rooftop terrace room , ensuite bathroom",13660,Simon,Chamartín,Hispanoamérica,40.46,-3.68,private room,60,1,78,2020-09-20,0.58,1.00,180.00,Madrid,1,EUR,60.00,4.11,Single-listing host,Has reviews
1,21853,Bright and airy room,83531,Abdel,Latina,Cármenes,40.40,-3.74,private room,31,4,33,2018-07-15,0.42,2.00,364.00,Madrid,1,EUR,31.00,3.47,Multi-listing host,Has reviews
2,23001,Apartmento Arganzuela- Madrid Rio,82175,Jesus,Arganzuela,Legazpi,40.39,-3.70,entire home/apt,50,15,0,NaT,0.00,7.00,1.00,Madrid,0,EUR,50.00,3.93,Multi-listing host,No reviews
3,24805,Gran Via Studio Madrid,346366726,A,Centro,Universidad,40.42,-3.71,entire home/apt,92,5,10,2020-03-01,0.13,1.00,72.00,Madrid,1,EUR,92.00,4.53,Single-listing host,Has reviews
4,26825,Single Room whith private Bathroom,114340,Agustina,Arganzuela,Legazpi,40.39,-3.69,private room,26,2,149,2020-03-12,1.12,1.00,365.00,Madrid,1,EUR,26.00,3.30,Single-listing host,Has reviews

In [7]:
dashboard_columns = [
    "id",
    "name",
    "host_id",
    "host_name",
    "neighbourhood_group",
    "neighbourhood",
    "latitude",
    "longitude",
    "room_type",
    "price",
    "currency",
    "price_eur",
    "minimum_nights",
    "number_of_reviews",
    "last_review",
    "reviews_per_month",
    "calculated_host_listings_count",
    "availability_365",
    "city",
    "has_reviews",
    "review_status",
    "host_type",
]

df_powerbi = df_powerbi[dashboard_columns]

print("Power BI dataset shape:", df_powerbi.shape)
df_powerbi.head()

Power BI dataset shape: (219981, 22)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,currency,price_eur,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,city,has_reviews,review_status,host_type
0,6369,"Rooftop terrace room , ensuite bathroom",13660,Simon,Chamartín,Hispanoamérica,40.46,-3.68,private room,60,EUR,60.00,1,78,2020-09-20,0.58,1.00,180.00,Madrid,1,Has reviews,Single-listing host
1,21853,Bright and airy room,83531,Abdel,Latina,Cármenes,40.40,-3.74,private room,31,EUR,31.00,4,33,2018-07-15,0.42,2.00,364.00,Madrid,1,Has reviews,Multi-listing host
2,23001,Apartmento Arganzuela- Madrid Rio,82175,Jesus,Arganzuela,Legazpi,40.39,-3.70,entire home/apt,50,EUR,50.00,15,0,NaT,0.00,7.00,1.00,Madrid,0,No reviews,Multi-listing host
3,24805,Gran Via Studio Madrid,346366726,A,Centro,Universidad,40.42,-3.71,entire home/apt,92,EUR,92.00,5,10,2020-03-01,0.13,1.00,72.00,Madrid,1,Has reviews,Single-listing host
4,26825,Single Room whith private Bathroom,114340,Agustina,Arganzuela,Legazpi,40.39,-3.69,private room,26,EUR,26.00,2,149,2020-03-12,1.12,1.00,365.00,Madrid,1,Has reviews,Single-listing host

In [8]:
df_powerbi.info()

<class 'pandas.DataFrame'>
RangeIndex: 219981 entries, 0 to 219980
Data columns (total 22 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              219981 non-null  int64
 1   name                            219981 non-null  str
 2   host_id                         219981 non-null  int64
 3   host_name                       219981 non-null  str
 4   neighbourhood_group             68494 non-null   str
 5   neighbourhood                   219981 non-null  str
 6   latitude                        219981 non-null  float64
 7   longitude                       219981 non-null  float64
 8   room_type                       219981 non-null  str
 9   price                           219981 non-null  int64
 10  currency                        219981 non-null  str
 11  price_eur                       219981 non-null  float64
 12  minimum_nights                  219981 non-null  int64
 13  number_of_reviews               219981 non-null  int64
 14  last_review                     152365 non-null  datetime64[us]
 15  reviews_per_month               219858 non-null  float64
 16  calculated_host_listings_count  208519 non-null  float64
 17  availability_365                208519 non-null  float64
 18  city                            219981 non-null  str
 19  has_reviews                     219981 non-null  int64
 20  review_status                   219981 non-null  str
 21  host_type                       219981 non-null  str
dtypes: datetime64[us](1), float64(6), int64(6), str(9)
memory usage: 36.9 MB

In [9]:
missing_summary = (
    df_powerbi
    .isna()
    .sum()
    .reset_index()
)

missing_summary.columns = ["column", "missing_count"]
missing_summary["missing_pct"] = (
    missing_summary["missing_count"] / len(df_powerbi) * 100
).round(2)

missing_summary.sort_values("missing_pct", ascending=False)

                            column  missing_count  missing_pct
4              neighbourhood_group         151487        68.86
14                     last_review          67616        30.74
16  calculated_host_listings_count          11462         5.21
17                availability_365          11462         5.21
15               reviews_per_month            123         0.06
0                               id              0         0.00
5                    neighbourhood              0         0.00
3                        host_name              0         0.00
2                          host_id              0         0.00
1                             name              0         0.00
6                         latitude              0         0.00
7                        longitude              0         0.00
8                        room_type              0         0.00
9                            price              0         0.00
13               number_of_reviews              0         0.00
12                  minimum_nights              0         0.00
11                       price_eur              0         0.00
10                        currency              0         0.00
18                            city              0         0.00
19                     has_reviews              0         0.00
20                   review_status              0         0.00
21                       host_type              0         0.00

In [10]:
summary_by_city = (
    df_powerbi
    .groupby("city")
    .agg(
        total_listings=("id", "count"),
        total_hosts=("host_id", "nunique"),
        avg_price_eur=("price_eur", "mean"),
        median_price_eur=("price_eur", "median"),
        avg_reviews=("number_of_reviews", "mean"),
        avg_reviews_per_month=("reviews_per_month", "mean"),
        avg_availability=("availability_365", "mean"),
        listings_with_reviews=("has_reviews", "sum"),
        multi_listing_host_listings=(
            "host_type",
            lambda x: (x == "Multi-listing host").sum()
        )
    )
    .reset_index()
)

summary_by_city["pct_listings_with_reviews"] = (
    summary_by_city["listings_with_reviews"] /
    summary_by_city["total_listings"] * 100
).round(2)

summary_by_city["pct_multi_listing_host_supply"] = (
    summary_by_city["multi_listing_host_listings"] /
    summary_by_city["total_listings"] * 100
).round(2)

summary_by_city

,city,total_listings,total_hosts,avg_price_eur,median_price_eur,avg_reviews,avg_reviews_per_month,avg_availability,listings_with_reviews,multi_listing_host_listings,pct_listings_with_reviews,pct_multi_listing_host_supply
0,London,85050,53473,140.72,96.60,17.47,0.92,118.48,65048,41518,76.48,48.82
1,Madrid,19610,11318,129.32,58.00,31.87,0.80,159.16,13981,10772,71.30,54.93
2,Milan,18322,12213,115.09,73.50,23.72,0.58,153.51,13260,8078,72.37,44.09
3,New_York,48884,37455,140.53,97.52,23.27,1.09,112.78,38833,16583,79.44,33.92
4,Sydney,36653,27213,124.64,81.60,12.18,0.77,97.37,24841,13214,67.77,36.05
5,Tokyo,11462,2954,89.94,60.04,26.04,1.93,NaN,9785,0,85.37,0.00

In [11]:
summary_by_neighbourhood = (
    df_powerbi
    .groupby(["city", "neighbourhood"])
    .agg(
        total_listings=("id", "count"),
        avg_price_eur=("price_eur", "mean"),
        median_price_eur=("price_eur", "median"),
        avg_reviews=("number_of_reviews", "mean"),
        avg_availability=("availability_365", "mean")
    )
    .reset_index()
    .sort_values(["city", "total_listings"], ascending=[True, False])
)

summary_by_neighbourhood.head()

,city,neighbourhood,total_listings,avg_price_eur,median_price_eur,avg_reviews,avg_availability
32,London,Westminster,9586,248.69,161.00,19.30,147.72
29,London,Tower Hamlets,8240,105.45,82.80,18.72,114.11
11,London,Hackney,6275,110.13,86.25,14.76,75.69
19,London,Kensington and Chelsea,6018,249.86,172.50,16.10,147.15
5,London,Camden,5971,166.09,115.00,22.00,124.25

In [18]:
main_output_path = output_dir / "airbnb_powerbi.csv"
city_summary_output_path = output_dir / "airbnb_powerbi_summary_by_city.csv"
neighbourhood_summary_output_path = output_dir / "airbnb_powerbi_summary_by_neighbourhood.csv"

df_powerbi.to_csv(main_output_path, index=False)
summary_by_city.to_csv(city_summary_output_path, index=False)
summary_by_neighbourhood.to_csv(neighbourhood_summary_output_path, index=False)

print("Power BI datasets exported successfully:")
print(main_output_path)
print(city_summary_output_path)
print(neighbourhood_summary_output_path)

Power BI datasets exported successfully:
..\data\processed\powerbi\airbnb_powerbi.csv
..\data\processed\powerbi\airbnb_powerbi_summary_by_city.csv
..\data\processed\powerbi\airbnb_powerbi_summary_by_neighbourhood.csv

## Summary
This PR prepares the final dashboard-ready datasets for the Airbnb multi-city Power BI report.

## Scope
- Load the cleaned master dataset
- Add business-friendly segmentation fields
- Keep both technical and business-friendly review fields
- Create host_type for host behavior analysis
- Create review_status for dashboard readability
- Export main Power BI dataset
- Export city-level summary dataset
- Export neighbourhood-level summary dataset

## Why
These datasets allow Power BI to consume clean, business-ready data for dashboard pages covering price, demand, availability, location, and host behavior.

## Environment
This project is managed with uv.

## Related Kanban Tickets
EPIC 6 - Ticket 15: Prepare dataset for Power BI

## Next steps
- Build Power BI dashboard pages
- Add screenshots to repository
- Prepare dashboard demo narrative